version: '3.4'
#get initial password:
#$ docker exec jenkins cat /var/jenkins_home/secrets/initialAdminPassword
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    restart: always
    ports:
      - 9000:8080
      - 50000:50000
    volumes:
      - ~/jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/local/bin/docker:/usr/local/bin/docker