version: '3.4'

x-common-variables: &common-variables
  MYSQL_DATABASE: 'db'
  MYSQL_USER: 'user'
  MYSQL_PASSWORD: 'password'
  MYSQL_ROOT_PASSWORD: 'password'
  MYSQL_PORT: '3306'

services:
  mysql:
    container_name: mysql
    image: mysql:latest
    restart: always
    environment:
      <<: *common-variables
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - mysql-volume:/var/lib/mysql

volumes:
  mysql-volume: